server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "${FRONTEND_URL:http://localhost:5173}"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true
      routes:
        - id: auth-service
          uri: ${AUTH_SERVICE_URL:http://localhost:8081}
          predicates:
            - Path=/auth/**
        - id: ingestion-service
          uri: ${INGESTION_SERVICE_URL:http://localhost:8082}
          predicates:
            - Path=/customers/**
          filters:
            - AuthenticationFilter
        - id: golden-record-service
          uri: ${GOLDEN_RECORD_SERVICE_URL:http://localhost:8084}
          predicates:
            - Path=/golden/**
          filters:
            - AuthenticationFilter
